import { Data } from "./Data"
import PageServices from "../PageServices"
import SVGComponent from "./SVGComponent"

export const metadata = {
    title: 'Data Backup and Disaster Recovery',
    description: 'Generated by create next app',
  }
  
export default function DataBackup() {
    return <PageServices data={Data} SVGComponent={SVGComponent} />
}