

export const metadata = {
    title: 'Company',
    description: 'Generated by create next app',
  }
  
export default function Company() {
    return (
        <>
            <h1>Company</h1>
        </>
    )
}