import { Data } from "./Data"
import PageServices from "../PageServices"
import SVGComponent from "./SVGComponent";

export const metadata = {
    title: 'Business Messaging',
    description: 'Generated by create next app',
}
  
export default function BusinessMessaging() {
    return <PageServices data={Data} SVGComponent={SVGComponent} />
}