import { Data } from "./Data"
import PageServices from "../PageServices"
import SVGComponent from "./SVGComponent"

export const metadata = {
    title: 'Network Security and Compliance',
    description: 'Generated by create next app',
  }
  
export default function NetworkSecurity() {
    return <PageServices data={Data} SVGComponent={SVGComponent} />
}