import { Data } from "./Data"
import PageServices from "../PageServices"
import SVGComponent from "./SVGComponent"

export const metadata = {
    title: 'Software and Hardware Management',
    description: 'Generated by create next app',
  }
  
export default function SoftwareHardware() {
    return <PageServices data={Data} SVGComponent={SVGComponent} />
}