import ITConsulting from "./ItConsulting"

export const metadata = {
    title: 'IT Consulting',
    description: 'Generated by create next app',
}

export default function Page() {
    return <ITConsulting />
}