


export const metadata = {
    title: 'Why Vfix',
    description: 'Generated by create next app',
  }

export default function WhyVfix(){
    return(
        <div>
            <h1>WhyVfix</h1>
        </div>
    )

}