import { Data } from "./Data"
import PageServices from "../PageServices"


export const metadata = {
    title: 'DIRECT ROUTING FOR MICROSOFT TEAMS',
    description: 'Generated by create next app',
  }
  
export default function DirectRoutingMicrosoft() {
    return (
        <>
            <PageServices data={Data} />
        </>
    )
}