import Contact from "@/common/contactus/ContactUs";


export const metadata = {
    title: 'Contact Us',
    description: 'Generated by create next app',
  }

export default function Contactus(){
    return(
        <div>
            <Contact />
        </div>
    )

}