import Typography from "@/common/Typography"
import { Data } from "./Data"
import { Page } from "../pagestyle"
import { Button } from "@/common/MainStyle"
import { PageContainer, LeftSide, RightSide, HeadTitle, Title, Paragraph, ImageRiteSide, ParagraphContainer,OverviewContainer, VfixCaontainer, VfixHeadTitle, VfixCardContainer, VfixHead, ServicesContainer, ServicesHead, VfixParagraph, ServicesTitle,ServicesParagraph, ServicesCardContainer} from './PageStyle'
import VfixCards from './VfixCard'
import ServicesCard from "./ServicesCard"



export const metadata = {
    title: 'IT Consulting',
    description: 'Generated by create next app',
  }
  
export default function ITConsulting() {
    return (
        <Page>
            <PageContainer>
                <OverviewContainer>
                    <LeftSide>
                        <HeadTitle>
                            <Typography variant='h5'>
                                {Data.Overview.headTitle}
                            </Typography>
                        </HeadTitle>
                        <Title>
                            <Typography variant='h2'>
                                {Data.Overview.title}
                            </Typography>
                        </Title>
                        <ParagraphContainer>
                            <Paragraph >
                                <Typography variant='body4'>
                                    {Data.Overview.paragraph}
                                </Typography>
                            </Paragraph>
                        
                        </ParagraphContainer>
                        <Button>{Data.Overview.button}</Button>
                    </LeftSide>
                    <RightSide>
                        <ImageRiteSide src={Data.Overview.img} width={700} height={700} alt={Data.Overview.title}/>
                    </RightSide>
                </OverviewContainer>
                <ServicesContainer>
                    <ServicesHead>
                        <ServicesTitle>
                            <Typography variant='h2'>
                                {Data.Overview.ourServicesTitle}
                            </Typography>
                        </ServicesTitle>
                        <ServicesParagraph>
                            <Typography variant='body4'>
                                {Data.Overview.ourServicesParagraph}
                            </Typography>
                        </ServicesParagraph>
                    </ServicesHead>
                    <ServicesCardContainer>
                        {
                            Data.Overview.ourServices.map((card, index) => (
                                <ServicesCard 
                                    key={index}
                                    title={card.title}
                                    content={card.paragraph}
                                    urlImage={card.img}
                                />
                            ))
                        }
                    </ServicesCardContainer>
                </ServicesContainer>
                <VfixCaontainer>
                    <VfixHead>
                        <VfixHeadTitle>
                            <Typography variant='h2'>
                                {Data.Overview.howCanVfixTitle}
                            </Typography>
                        </VfixHeadTitle>
                        <VfixParagraph>
                            <Typography variant='body4'>
                                {Data.Overview.howCanVfixParagraph}
                            </Typography>
                        </VfixParagraph>
                    </VfixHead>
                            
                            <VfixCardContainer>
                                {
                                    Data.Overview.howCanVfix.map((card, index) => (
                                        <VfixCards 
                                            key={index}
                                            title={card.title}
                                            content={card.paragraph}
                                            urlImage={card.img}
                                        />
                                    ))
                                }
                            </VfixCardContainer>
                </VfixCaontainer>
                
            </PageContainer>
        </Page>
    )
}