

export const metadata = {
    title: 'Cloud Phone System',
    description: 'Generated by create next app',
  }
  
export default function CloudPhoneSystem() {
    return (
        <>
            <h1>Cloud Phone System</h1>
        </>
    )
}