import { Data } from "./Data"
import PageServices from "../PageServices"
import SVGComponent from "./SVGComponent"

export const metadata = {
    title: 'Cloud Services and Migration',
    description: 'Generated by create next app',
  }
  
export default function CloudServices() {
    return <PageServices data={Data} SVGComponent={SVGComponent} />
}