
import {Container, Title, Paragraph, Button, Section} from './pagestyle'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <Container>
      <Section>
        <Title>Hello</Title>
        <Paragraph>This is a Paragraph</Paragraph>
        <Button>Click Me!</Button>
      </Section>
      <Section>
        <Title>Hello</Title>
        <Paragraph>This is a Paragraph</Paragraph>
        <Button>Click Me!</Button>
      </Section>
      <Section>
        <Title>Hello</Title>
        <Paragraph>This is a Paragraph</Paragraph>
        <Button>Click Me!</Button>
      </Section>
      <Section>
        <Title>Hello</Title>
        <Paragraph>This is a Paragraph</Paragraph>
        <Button>Click Me!</Button>
      </Section>
    </Container> 
    
  )
}

