import { Data } from "./Data"
import PageServices from "../PageServices"

export const metadata = {
    title: 'Mobile and Desktop App',
    description: 'Generated by create next app',
  }
  
export default function MobileDesktopApp() {
    return (
        <>
            <PageServices data={Data} />
        </>
    )
}