import { Data } from "./Data"
import PageServices from "../PageServices"

export const metadata = {
    title: 'Proactive Monitoring and Maintenance',
    description: 'Generated by create next app',
  }
  
export default function ProactiveMonitoring() {
    return (
        <>
            <PageServices data={Data} />
        </>
    )
}