import Typography from "@/common/Typography"
import { Data } from "./Data"
import PageServices from "../PageServices"

export const metadata = {
    title: 'Cloud Content Center',
    description: 'Generated by create next app',
  }
  
export default function CloudContentCenter({data}) {
    return (
        <>
            <PageServices data={Data} />
        </>
    )
}