export const color = {
    Red100: '#FD346E',
    Green100: '#01D0A2',
    Green200: '#00D59C',
    Blue100: '#009CD5',
    Purple100: '#9747FF',
    White: '#FAFAFA',
    Black: '#000000',
    // background: linear-gradient(90deg, #00D59C 0%, #009CD5 100%);

}

export const Theme ={
    typography: {
        component: {
            h1: 'h1',
            h2: 'h2',
            h3: 'h3',
            h4: 'h4',
            h5: 'h5',
            h6: 'h6',
            subline1: "p",
            subline2: "p",
            body1: "p",
            body2: "p",
            button: "span",
            caption: "span",
            overLine: "span",
        },
        fontSize: {
            h1: "64px",
            h2: "48px",
            h3: "33px",
            h4: "23px",
            h5: "16px",
            h6: "14px",
            subline1: "21px",
            subline2: "18px",
            body1: "24px",
            body2: "18px",
            button: "16px",
            caption: "14px",
            overLine: "13px",
        },
        lineHeight: {
            h1: "60px",
            h2: "40px",
            h3: "30px",
            h4: "20px",
            h5: "15px",
            h6: "12px",
            subline1: "24px",
            subline2: "20px",
            body1: "24px",
            body2: "20px",
            button: "24px",
            caption: "20px",
            overLine: "16px",
        },
        fontWeights: {
            thin: "100",
            extraLight: "200",
            light: "300",
            regular: "400",
            medium: "500",
            semiBold: "600",
            bold: "700",
        },
    },
    
}
