name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Archive project
        run: |
          tar czf vfixmsp.tar.gz package.json next.config.js jsconfig.json src public

      - name: Decode SSH key
        env:
          SSH_PRIVATE_KEY_BASE64: ${{ secrets.SSH_PRIVATE_KEY_BASE64 }}
        run: |
          echo "$SSH_PRIVATE_KEY_BASE64" | base64 --decode > $HOME/VFix.pem
          chmod 600 ${HOME}/VFix.pem

      - name: Copy project to server
        env:
          IP: ${{secrets.IP}}
        run: |
          scp -i $HOME/VFix.pem -o StrictHostKeyChecking=no vfixmsp.tar.gz ubuntu@$IP:~
        
      - name: Deploy project
        env:
          IP: ${{secrets.IP}}
        run: |
          ssh -i $HOME/VFix.pem -o StrictHostKeyChecking=no ubuntu@$IP "
            mkdir -p vfixmsp-temp &&
            tar xf vfixmsp.tar.gz -C vfixmsp-temp 2> /dev/null &&
            rm vfixmsp.tar.gz &&
            cd vfixmsp-temp &&
            find . -name '._*' -exec rm {} \; &&
            npm i &&
            npm run build &&
            cd .. &&
            rm -rf vfixmsp &&
            mv vfixmsp-temp vfixmsp &&
            cd vfixmsp &&
            pm2 delete vfixmsp --silent &&
            pm2 start npm --name 'VFix-msp' -- start
          "
        